
input_str = '''
Gender: <gender> | Age: <age> | Years_sincePD: <years_pd> | Nonlevodopa dose: <nldopa_dose>
Six previous cycles of UPDRS scores (from old to new): <u1>, <u2>, <u3>, <u4>, <u5>, <u6>
'''

problem = '''
## Information

The patient you need to treat has the following attributes:

Gender: <gender> | Age: <age> | Years_sincePD: <years_pd> | Nonlevodopa dose: <nldopa_dose>
Six previous cycles of UPDRS scores (from old to new): <u1>, <u2>, <u3>, <u4>, <u5>, <u6>

## Relevant patient information

Here, you will be provided with information and expert treatment data from some similar patients as reference. You can make similar decisions based on patients in similar situations.

<rag_context>

Please provide your treatment plan based on this input.
'''


Example_prompt = '''
**Example input:**
<i1>

**Example output:**
<o1>

'''

rag_content = '''\
Gender: <gender> | Age: <age> | Years_sincePD: <years_pd> | Nonlevodopa dose: <nldopa_dose>
Six previous cycles of UPDRS scores (from old to new): <u1>, <u2>, <u3>, <u4>, <u5>, <u6>
best_treatment_plan = <best_treat>\n
'''

rag_content_mcts = '''\
Gender: <gender> | Age: <age> | Years_sincePD: <years_pd> 
Medication history (from old to new): <medication_history>
Nonlevodopa dose (from old to new): <nldopa_history>
Six previous cycles of UPDRS scores (from old to new): <u1>, <u2>, <u3>, <u4>, <u5>, <u6>
Recommended prescriptions generated by ML method: <good_examples>
Example prescriptions not recommended: <bad_examples>
'''


example = '''

**Example input:**

Gender: male | Age: 66.7 | Years_sincePD: 8.9 | Nonlevodopa dose: 21.8
Six previous cycles of UPDRS scores (from old to new): 13.14, 33.74, 37.61, 25.84, 52.97, 52.97


**Example output:**
[[0, 0, 100, 100], [200, 200, 0, 0], []]
'''


llm_system_message = '''You are a doctor specializing in Parkinson's disease treatment. We present information about a given patient, along with some machine-learning (ML)-generated treatment plans for other similar cases. You need to analyze the patient information and similar cases, and subsequently provide the formatted prescription following format specified below.

## Explanations of related terms

1. UPDRS Score: The score of the Unified Parkinson Disease Rating Scale (UPDRS) ranges from 0 to 53 (99th-percentile), with higher scores indicating more severe symptoms. Each adjacent score is evaluated approximately a year apart.
2. Nonlev: Nonlev is the sum of the daily doses of other non-levodopa drugs (e.g., dopamine, MAO-B inhibitors, and COMT inhibitors) prescribed by a physician and is measured as the daily equivalent of L-dopa in milligrams.
3. The medication history followed the same format as the given treatment plans for Levodopa and equivalent Levodopa doses for Nonlev and was also prescribed approximately a year apart.
4. The treatment plan is a list of three sublists, which include L-dopa IR ("immediate release"), L-dopa CR ("controlled release"), and Rytary (which is an extended-release form of L-dopa) medication data. These medications differ in how quickly they release L-dopa into patients' bloodstreams. The sublist shows the dosage and frequency of each drug in milligrams. For example, the treatment plan `[[200, 0, 0], [], [0, 95, 95]]` indicates that for L-dopa IR and Rytary, three equally spaced doses are administered during the 17 waking hours each day, with the first dose being 200 mg of L-dopa IR. The last two doses of Rytary are 95 mg each.
5. We use ML methods to obtain prescriptions that provide four alternatives classified as recommended and not recommended, respectively. Specifically, each alternative is accompanied by the predicted UPDRS score after 3 years as predicted by the neural network.
6. Patients who have not been diagnosed with PD will be listed as `N/A` in the `Years_sincePD` metric. These patients may be prescribed medication for prevention or may exhibit some motor abnormalities and disorders, the extent of which might be reflected in the UPDRS score.

## Factors to consider

We present some of the main considerations when deciding which medication plan to prescribe to a given patient, with the intention of illustrating how these factors guide prescription decisions. Specifically, this includes several aspects:

**The Patient's Information:** Age, gender, number of years since the diagnosis of PD, medication history, and history of disease progression obtained from the UPDRS score may significantly influence prescription preferences, including the suitability and incompatibility of certain drug combinations.

**Similar Cases:** We also provide several similar cases and the corresponding recommended treatment plans, specifically:

- For each similar case, the patient's information is presented in the same format as the given patient. The information is generally similar to the patient being prescribed, but there are still some differences.
- Several recommended and unrecommended treatment plans are given for each similar case, and UPDRS scores predicted by machine learning are also provided. These treatment plans should also be appropriate to a certain extent for the given patient. Specifically, these plans are judged not only by predicted UPDRS scores, where differences greater than ±3 are generally considered significant, but also by considering the potential differences in subsequent disease development these medication recommendations may cause and whether they align with the actual condition of the patient. After conducting a comprehensive analysis, the recommended plans for certain similar cases with higher priority may be selected as the basis for modification.
- It should be noted that due to the differences that still exist in similar cases, there will be variations in the outcome of treatment plan candidates, which should also be taken into account.

**Final Output:** The prescription for the final output should strictly follow the format described below.

## Output Guide and Format

Your final output should contain only a simple analysis of about 200 words, and a Python code block containing the final recommended prescription after an additional explanation.

The brief analysis includes the following: (a) A brief analysis of Important information about the patient that may affect the decision of the treatment; (b) A brief analysis of similar cases and an overall analysis of recommended treatment plans. (c) Based on the comprehensive analysis, indicate the final prescription strategy and whether it is modified based on a certain treatment plan from the similar cases. (d) What adjustments (alter the frequency/dosage, change the medicine type...) and medication strategies have been made to further improve the potential effect to lower the UPDRS score. 

Then, based on the above analysis, the prescription which could maximize the decrease of UPDRS score should be obtained from similar cases or information from the given patient. The prescription contains the frequency and dosage of L-dopa IR, L-dopa CR, and Rytary intake on a daily basis. You should output the additional textual summary to specifically specify the dose and frequency of each medicine, then output the corresponding formatted prescription in python code block, as we explained in the 4) of the section "Explanations of related terms".  

For example, for following **textual** explanation:

- **Frequency:** 3 doses
- **Medicine and Dosage:** (1) Morning: 200mg L-dopa IR (2) Noon: N/A (3) Evening: 95mg Rytary
- **Additional comment:** ...

The corresponding **formatted** output is:

```python
[[200, 0, 0], [0, 0, 0], [0, 0, 95]]
```

Note that treatment plans for the given patient include a range of possible prescription. However, you should analyze the patient's information, evaluating possible differences and choosing the treatment that is most promising to reduce the patient's UPDRS in a long-term perspective.

## Notes

- 1 dose / 2 doses (Morning, Evening) / 3 doses (Morning, Noon, Evening) / 4 doses (Morning, Noon, Afternoon, Evening)
- For non-levodopa (Nonlev) drugs, no advice is required, as this part is directly prescribed by professional physicians.
- To facilitate pattern matching, you should only output one python block in the `### Formatted Treatment Plan` section.
- For ML-predicted prescriptions, as the decision space is discrete and limited, there may be other doses or frequencies that work better but are not included in the recommended prescription list.
- The sample prescriptions given in the above (for example, `[[200, 0, 0], [], [0, 95, 95]]` and `[[], [100, 100, 0, 0], [0, 0, 245, 245]]`) are only used to illustrate the output format and meaning and **DO NOT** constitute any treatment recommendations. You should prescribe based on the actual situation.
''' 

llm_user_message = '''\
\n''' 

llm_user_message_worag = '''\
## Patient Information to be Analyzed 

The information of patient you need to analyze is:

<patient_information>

## Relative cases

Several similar patient information given below, we adopt ML methods to predict the recommended treatment plans, and obtain explanations and suggestions output by LLMs.

<rag_context>

\n''' 
